// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Aplicacao.Models
{
    [Index("Nome", Name = "IX_Pessoa", IsUnique = true)]
    public partial class Pessoa
    {
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        public int? Idade { get; set; }
        [Column("CPF")]
        [StringLength(10)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Key]
        public int Id { get; set; }
    }
}