// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Aplicacao.Models
{
    [Index("NomeCarro", Name = "IX_Veiculos_1")]
    public partial class Veiculos
    {
        [StringLength(50)]
        [Unicode(false)]
        public string NomeCarro { get; set; }
        public int? Ano { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ValorFipe { get; set; }
        [Key]
        public int Id { get; set; }
    }
}